name: eldorado_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  
  # Immutability
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Network
  dio: ^5.9.0
  
  # Logging
  logger: ^2.3.0
  
  # Navigation
  go_router: ^14.2.1
  
  # UI
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.1
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/cripto_currencies/
    - assets/fiat_currencies/